#!/usr/bin/env bash

# Only run in the bridge-app-ui repository
if [[ "$(pwd)" != "$HOME/Programs/bridge/bridge-app-ui"* ]]; then
    exit 0
fi

if [[ "$1" == "0000000000000000000000000000000000000000" ]]; then
    basePath="$HOME/Programs/bridge/bridge-app-ui/main"
    paths=(.env .mcp.json .envrc)

    for path in "${paths[@]}"; do
        if [[ -f "$basePath/$path" ]]; then
            ln -sf "$basePath/$path" "$(pwd)/$path"
            echo "✅ Copied $path"
        fi
    done

    direnv allow
fi
